# Generated by Django 3.1.6 on 2021-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_restaurant', models.CharField(max_length=200)),
                ('adresse_restaurant', models.CharField(max_length=400)),
                ('code_postal_restaurant', models.CharField(max_length=200)),
                ('ville_restaurant', models.CharField(max_length=200)),
                ('pays_restaurant', models.CharField(max_length=200)),
                ('telephone_restaurant', models.CharField(max_length=400)),
            ],
        ),
    ]
